
import { jsPDF } from 'jspdf';
import { LessonContent } from '../types';

export const exportLessonToPDF = (lesson: LessonContent) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let cursorY = 20;

  // Utility to add text with wrapping
  const addWrappedText = (text: string, fontSize: number, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, pageWidth - (margin * 2));
    
    // Check for page overflow
    if (cursorY + (lines.length * (fontSize * 0.5)) > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      cursorY = margin;
    }
    
    doc.text(lines, margin, cursorY);
    cursorY += (lines.length * (fontSize * 0.5)) + 5;
  };

  // Prepare Title Wrapping
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(lesson.title.toUpperCase(), pageWidth - (margin * 2));
  
  // Dynamic header height based on title lines
  const headerHeight = Math.max(40, (titleLines.length * 10) + 15);

  // Header Background
  doc.setFillColor(255, 107, 0); // Neo Orange
  doc.rect(0, 0, pageWidth, headerHeight, 'F');
  doc.setDrawColor(0);
  doc.setLineWidth(1);
  doc.line(0, headerHeight, pageWidth, headerHeight);

  // Render Title in Header
  doc.setTextColor(0);
  doc.setFontSize(22);
  // Center text vertically in the dynamic header
  doc.text(titleLines, margin, (headerHeight / 2) + 2, { baseline: 'middle' });
  
  cursorY = headerHeight + 15;

  const sections = [
    { title: "I. OVERVIEW", content: lesson.overview },
    { title: "II. CLINICAL ANATOMY", content: lesson.anatomy },
    { title: "III. JEWELRY STANDARDS", content: lesson.jewelrySpecs || "N/A" },
    { title: "IV. SENSATION & HEALING", content: lesson.painAndHealing || "N/A" },
    { title: "V. TOOLS & EQUIPMENT", content: lesson.tools },
    { title: "VI. TRAY SETUP", content: lesson.setup || "N/A" },
    { title: "VII. TECHNICAL PROCEDURE", content: lesson.procedure },
    { title: "VIII. AFTERCARE GUIDELINES", content: lesson.aftercare },
    { title: "IX. COMPLICATIONS & MANAGEMENT", content: lesson.complications },
    { title: "X. CLINICAL RED FLAGS", content: lesson.redFlags || "N/A" },
    { title: "XI. CONSULTATION SCRIPT", content: lesson.clientDiscussion || "N/A" },
  ];

  sections.forEach(section => {
    if (section.content && section.content !== "N/A") {
      addWrappedText(section.title, 14, true);
      addWrappedText(section.content, 11);
      cursorY += 5;
    }
  });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Generated by Piercer's Pro-Study - Professional Technical Reference", margin, footerY);

  doc.save(`${lesson.title.replace(/\s+/g, '_')}_Technical_Report.pdf`);
};
